### ISSUE TITLE
why use try ad catch in sellInfoHandler

### ISSUE THREAD

**Issue by Karyum** [FACN8/Shop-Titans#8]
here 
https://github.com/FACN8/Shop-Titans/blob/master/src/handlers.js#L85-L96

**Comment by FrancisA2000** [comment]
because it was kinda tricky to predict if the received  value have a stringify value or quary value , 
And for that reason if I used JSON.parse at fisrt it will work only if it stringify value else it will throw error, that means its quary value. 
I hope I was clear enough.
